subsets:
  train: ../datasets/synthetic/subsets/by_date/train_subset_indices_0.1.pt
  valid: ../datasets/synthetic/subsets/by_date/valid_subset_indices_0.1.pt
  valid2: ../datasets/synthetic/subsets/by_date/valid2_subset_indices_0.1.pt
  test: ../datasets/synthetic/subsets/by_date/test_subset_indices_0.1.pt