data:
  dataset: electricity
  format: csv
  path: ../datasets/electricity/
  indiv_split: ../datasets/electricity/splits/indiv
  date_split: ../datasets/electricity/splits/date
  by_idx: dates
  seed:
  mean: 2500
  std: 15000

model:
  lags: 336
  horizon: 24
  name: DLinear
  normalization: global

training:
  retrain: True
  loss: MMSE
  bs: 128
  lr: 0.0001
  epochs: 100

misc:
  seed:
  output_dir: ../outputs/
  benchmark: False
  save_name:
  verbose: 1

defaults:
  - _self_
  - model_configs: DLinear
  - fed: fed_all
  - subset: full