data:
  dataset: electricity
  format: csv
  path: ../datasets/
  indiv_split: ../datasets/indiv
  date_split: ../datasets/date
  subset:
    train: ../datasets/train_subset_indices_0.1.pt
    valid: 1
    valid2: 1
    test: 1
  seed:
  mean: 2500
  std: 15000

fed:
  splits:
    ../datasets/node_0_indices.pt: ../datasets/node_0/date
    ../datasets/node_1_indices.pt: ../datasets/node_1/date
    ../datasets/node_2_indices.pt: ../datasets/node_2/date
  subsets: [0.1 0.1 0.1]
  epochs: 3
  rounds: 5

model:
  lags: 336
  horizon: 24
  name: linear
  normalization: 1

training:
  retrain: True
  loss: NMSE
  bs: 4
  lr: 0.0001
  epochs: 1

misc:
  seed:
  output_dir: ../outputs/
  benchmark: False
  save_name:
  verbose: True

defaults:
  - _self_
  - model_configs: linear