data:
  dataset: electricity
  path: ../datasets/
  rebuild: False
  reset: False
  example_name : rand
  format: csv
  indiv_split: 0.7
  date_split: 0.7
  seed:

model:
  lags: 336
  horizon: 24
  name: linear
  revin: False

training:
  retrain: True
  loss: MSE
  normalized: True
  bs: 8
  subset_data: 1
  lr: 0.0001
  schedule: False
  n_prints: 10
  n_evals: 100

misc:
  seed:
  output_dir: outputs/
  save_name:
  verbose: True

defaults:
  - _self_
  - model_configs: linear