data:
  dataset: electricity
  format: csv
  path: ../datasets/
  indiv_split: ../datasets/indiv
  date_split: ../datasets/date
  subset:
    train: ../datasets/train_subset_indices_0.1.pt
    valid: 1
    valid2: 1
    test: 1
  seed:

fed:
  splits:
    ../datasets/node_0_indices.pt: [0.7, 0.7]
    ../datasets/node_1_indices.pt: [0.7, 0.7]
    ../datasets/node_2_indices.pt: [0.7, 0.7]

model:
  lags: 336
  horizon: 24
  name: linear
  revin: False

training:
  retrain: True
  loss: MSE
  normalized: True
  bs: 4
  lr: 0.0001

misc:
  seed:
  output_dir: ../outputs/
  benchmark: False
  save_name:
  verbose: True

defaults:
  - _self_
  - model_configs: linear