data:
  dataset: electricity
  path: datasets/
  rebuild: False
  reset: False
  example_name : rand
  format: csv
  indiv_split: 0.7
  date_split: 0.7
  seed:
  indiv:

model:
  lag: 336
  horizon: 24

misc:
  seed:
  outputdir: outputs/
  smth: 1