training:
  init:
  freeze_core: False
  retrain: True
  loss: MSE
  bs: 28
  lr: 0.0001
  epochs: 10
  eval_freq: 10
  print_freq: 10

task:
  lags: 336
  horizon: 48
  splits:
  rounds: 10
  sampled_clients: 1
  fedmin: False
  
load:
  rebuild: False
  example: False
  replot: False
  heterogeneity: False
  clusters: False
  logs: True

misc:
  seed: 1
  output_dir: ../outputs/new/
  save_name:
  verbose: 1
  complete_evaluation: False

defaults:
  - _self_
  - data: electricity
  - model: PatchTST
  - normalization: instance
