training:
  init:
  freeze_core: False
  retrain: True
  loss: MSE
  bs: 28
  lr: 0.0001
  epochs: 10
  eval_freq: 10
  print_freq: 10

task:
  lags: 336
  horizon: 48
  rebuild_pt: False
  new_example: False
  replot: False
  heterogeneity: False

misc:
  seed: 1
  output_dir: ../outputs/new/
  benchmark: True
  save_name:
  verbose: 1
  complete_evaluation: False

defaults:
  - _self_
  - data: electricity
  - model: PatchTST
  - normalization: instance
